
########################################################
# (Configuration)
########################################################

spring:
  datasource:
    url: jdbc:mysql://192.168.1.34:3306/test
    username: root
    password: zhangquanquan

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl.auto: create-drop
        show_sql: true

  redis:
    database: 1
    host: 172.17.0.2
    port: 6379
    password:
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    timeout: 5000



logging:
  level: debug
  level.com.quantum: debug
  path: ./log/
  file: api.log